@startuml

title __CUSTOMER's Class Diagram__\n

  namespace Customer {
    class Customer.CustomerBooking {
        - dates : String
        - duration : int
        - equipment : String
        - refreshments : String
        - refreshmentsTime : String
        - roomID : int
        - timePeriod : String
        + CustomerBooking()
        + getDates()
        + getDuration()
        + getEquipment()
        + getRefreshments()
        + getRefreshmentsTime()
        + getRoomID()
        + getTimePeriod()
        + setDates()
        + setDuration()
        + setEquipment()
        + setRefreshments()
        + setRefreshmentsTime()
        + setRoomID()
        + setTimePeriod()
    }
  }
  

  namespace Customer {
    class Customer.CustomerController {
        - backButton : Button
        - currentBookingsLabel : Label
        - data : ObservableList<userBookings>
        - endDateColumn : TableColumn<userBookings, String>
        - endTimeColumn : TableColumn<userBookings, String>
        - myTable : TableView<userBookings>
        - newBookingButton : Button
        - refreshmentsColumn : TableColumn<userBookings, String>
        - refreshmentsTimeColumn : TableColumn<userBookings, String>
        - resourcesColumn : TableColumn<userBookings, String>
        - roomIDColumn : TableColumn<userBookings, Integer>
        - startDateColumn : TableColumn<userBookings, String>
        - startTimeColumn : TableColumn<userBookings, String>
        - welcomeLabel : Label
        + backToLogin()
        + deleteBooking()
        + initialize()
        + loadBookingData()
        - newBooking()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
