@startuml

title __ADMIN's Class Diagram__\n

  namespace Admin {
    class Admin.AccountData {
        - ID : StringProperty
        - accountType : StringProperty
        - email : StringProperty
        - firstname : StringProperty
        - lastname : StringProperty
        - password : StringProperty
        - username : StringProperty
        + AccountData()
        + IDProperty()
        + accountTypeProperty()
        + emailProperty()
        + firstnameProperty()
        + getAccountType()
        + getEmail()
        + getFirstname()
        + getID()
        + getLastname()
        + getPassword()
        + getUsername()
        + lastnameProperty()
        + passwordProperty()
        + setAccountType()
        + setEmail()
        + setFirstname()
        + setID()
        + setLastname()
        + setPassword()
        + setUsername()
        + usernameProperty()
    }
  }
  

  namespace Admin {
    class Admin.AdminController {
        ~ duration : int
        - DBOnlineLabel : Label
        - IDColumn : TableColumn<AccountData, String>
        - accountLabel : Label
        - accountTypeColumn : TableColumn<AccountData, String>
        - addAdminButton : Button
        - backgroundLabel : Label
        - caterersDashboardButton : Button
        - chart : PieChart
        - cleanersDashboardButton : Button
        - clearDB : Button
        - data : ObservableList<AccountData>
        - dbSizeLabel : Label
        - emailColumn : TableColumn<AccountData, String>
        - firstnameColumn : TableColumn<AccountData, String>
        - headingLabel : Label
        - lastnameColumn : TableColumn<AccountData, String>
        - myTable : TableView<AccountData>
        - passwordColumn : TableColumn<AccountData, String>
        - pieData : ObservableList
        - reloadButton : Button
        - usernameColumn : TableColumn<AccountData, String>
        + addAdmin()
        + backToLogin()
        + clearUpDB()
        + getDBSize()
        + initialize()
        + loadCustomerData()
        + openCaterersDashboard()
        + openCleanersDashboard()
        + refreshPage()
        + setPieData()
    }
  }
  

  namespace Admin {
    class Admin.adminCreation {
        - Heading : Label
        - backgroundLabel : Label
        - cancelButton : Button
        - emailField : TextField
        - errorLabel : Label
        - firstNameField : TextField
        - lastNameField : TextField
        - passwordField : PasswordField
        - registerButton : Button
        - usernameField : TextField
        + backToAdmin()
        + checkFormat()
        + registerLogic()
        + registerUser()
    }
  }
  

  namespace Admin {
    class Admin.userBookings {
        - endDate : LocalDate
        - endTime : LocalTime
        - refreshments : String
        - refreshmentsTime : String
        - resources : String
        - roomID : int
        - startDate : LocalDate
        - startTime : LocalTime
        - userID : int
        - username : String
        + getDuration()
        + getEndDate()
        + getEndTime()
        + getRefreshments()
        + getRefreshmentsTime()
        + getResources()
        + getRoomID()
        + getStartDate()
        + getStartTime()
        + getTodayDuration()
        + getUserID()
        + getUsername()
        + setEndDate()
        + setEndTime()
        + setRefreshments()
        + setRefreshmentsTime()
        + setResources()
        + setRoomID()
        + setStartDate()
        + setStartTime()
        + setUserID()
        + setUsername()
        + userBookings()
        + userBookings()
        + userBookings()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
